name: Build iOS and macOS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS
        # --no-codesign ကို ဖြုတ်လိုက်ပါ
        run: flutter build macos --release --dart-define=GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Build iOS
        # iOS မှာတော့ --no-codesign က ရှိရပါမယ်
        run: flutter build ios --release --no-codesign --dart-define=GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/*.app